### ISSUE TITLE
Feature request - cmake-version: 'latest'

### ISSUE THREAD

**Issue by carlosperate** [jwlawson/actions-setup-cmake#41]
To be able to automatically fetch the latest version available.

This is useful with a job matrix to test that libraries always compile with the latest version of CMake without having to constantly update the workflow file:

```yaml
jobs:
  build-test:
    strategy:
      matrix:
        # Oldest supported and newest release
        cmake: ['3.4.0', 'latest']
    steps:
      - name: Setup CMake ${{ matrix.cmake }}
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: ${{ matrix.cmake }}
```
