### ISSUE TITLE
Node.js 12 actions deprecated

### ISSUE THREAD

**Issue by AnHeuermann** [jwlawson/actions-setup-cmake#48]
## Description

When running a workflow with `actions-setup-cmake` I get the following warning:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16: actions/checkout, jwlawson/actions-setup-cmake, actions/checkout
```

Node12 is out of support and GitHub is running all actions on Node 16, see https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

## How to reproduce

Run a workflow with something like

```yaml
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.12
```
