### ISSUE TITLE
Use cache to avoid API rate limit exceeded for installation ID*

### ISSUE THREAD

**Issue by flagarde** [jwlawson/actions-setup-cmake#52]
Hello,

Thanks for this nice action it is very useful.
However, sometimes I'm using github action to test on hardware I don't have at disposal, so this involve a lot of push, this trigger the API rate limit exceeded for installation ID* even with GITHUB_TOKEN.

Do you think it could be a solution to add an option to use 'actions/cache@v3' to avoid this situation ?
like :

```yaml
- name: Setup CMake
  uses: jwlawson/actions-setup-cmake@v1.12
  with:
    cmake-version: '3.24.x'
    github-api-token: ${{ secrets.GITHUB_TOKEN }}
    cache : true
```

to download it and store it in a dedicated folder to avoid next download in case the 3.24.x is the same ?
