### ISSUE TITLE
Install latest version failed on windows

### ISSUE THREAD

**Issue by eeliu** [jwlawson/actions-setup-cmake#68]
## Version

```
Run jwlawson/actions-setup-cmake@v1.14
  with:
    cmake-version: latest
    github-api-token:

```
```
Expand-Archive :  is not a supported archive file format. .zip is the only supported archive file format.
At line:1 char:2[10](https://github.com/eeliu/pinpoint-c-agent/actions/runs/8325440524/job/22779083961#step:3:11)
+ ...  Ignore)) { Expand-Archive -LiteralPath 'D:\actions\action-eeliu\_wor ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:String) [Expand-Archive], IOException
    + FullyQualifiedErrorId : NotSupportedArchiveFileExtension,Expand-Archive
```
